workflows:
  godot-android:
    name: Godot Android Build
    max_build_duration: 30
    environment:
      vars:
        GODOT_VERSION: 4.1.1
        GODOT_EXEC_URL: https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
        GODOT_TEMPLATES_URL: https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
    scripts:
      - name: Download Godot Engine
        script: |
          wget -O godot.zip ${GODOT_EXEC_URL}
          unzip godot.zip -d godot
          chmod +x godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64
      - name: Install Export Templates
        script: |
          wget -O templates.tpz ${GODOT_TEMPLATES_URL}
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          unzip templates.tpz -d ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build Android APK
        script: |
          mkdir -p build
          godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64 --headless --export-release "Android" build/UnderworldEmpire.apk
    artifacts:
      - build/UnderworldEmpire.apk
